### ISSUE TITLE
Voice Settings (more DNS)

### ISSUE THREAD

**Issue by Qhiliqq** [easy-wi/developer#812] opened 2016-04-24 13:49 UTC
Include Dropdown for more default DNS domains.

For example:
Default is the hosters DNS like "example1.com" with dropdown for other DNS like "example2.com" and so on.
Infront of the dropdown is the actual text box for the subdomain like "private".

if you check "Use own DNS" the dropdown disappears and a new window appears were you can enter your own domain.

**Comment by ulrichblock** [comment] 2016-04-24 14:03
Duplicate of  #562

**Closed by ulrichblock** 2016-04-24 14:03 UTC
Labels: duplicate
