### ISSUE TITLE
Mobile CSS (broken - Android)

### ISSUE THREAD

**Issue by MikkelDK** [easy-wi/developer#1126] opened 2018-05-10 08:17 UTC
Hi,

I have found a error, where the "Dashboard" is broken, and i can't click on the "top" line, where i can get "GameServer" > it will require to "switch" to PC version via mobile, before it's possible.

Since i dont know, where to fix (i can show a little screenshot). - On the screen, i have paint a (arrow) where it's **NOT** possible to click on. i'm using Android :)

![screenshot_20180510-101007](https://user-images.githubusercontent.com/5301047/39859755-2f8e957e-543b-11e8-8585-b3ac03648dc4.png)

**Comment by MadMakz** [comment] 2018-07-21 11:41
What version of Easy-Wi?
I can't reproduce this on current stable other than #1052 wich is going to be fixed in upcoming stable.

**Comment by MikkelDK** [comment] 2018-07-22 07:43
Hi @MadMakz it works now, but i wont remember what i did.. since 10.may ;)

**Closed** 2018-08-14 18:45 UTC
