### ISSUE TITLE
Move Gameservers

### ISSUE THREAD

**Issue by Qhiliqq** [easy-wi/developer#827] opened 2016-05-04 12:52 UTC
Maybe adding to move GS from one host to another (in admin panel)

**Comment by Pandry** [comment] 2016-05-04 14:02
What do you mean?
Move Gameservers from one master server to another one?

**Comment by Qhiliqq** [comment] 2016-05-04 14:11
Jep exactly.

Without the moving services.

I make this while copying all files per rsync to the other root, but this could be done smoother and simple with a included script

**Comment by Pandry** [comment] 2016-05-04 14:15
Well...
It's a bit difficult...
A user could have some data in his server like maps or something else...
The panel should start a script that copy all the files in another server, creating the same user...
It's difficult..
It would be better (or at least I think) to make a new game server on another server and, after that, copy all the user data in the new server...

**Comment by ulrichblock** [comment] 2016-05-04 16:35
Duplicate of #4

**Closed by ulrichblock** 2016-05-04 16:35 UTC
Labels: duplicate
