### ISSUE TITLE
Add Mumble support

### ISSUE THREAD

**Issue by robingroppe** [easy-wi/developer#718] opened 2016-02-05 14:12 UTC
Hi,
it would be nice to see support for mumble in the voiceserver module.
Mumble got some awesome features that ts3 dont have.

-Opus Codec for minimal latency while beeing very high quality
-fully encrypted by default (ssl-rsa)
-Publickey / Privatekey authentication
-usable In-Game Overlay
-positional audio in a lot of games
-Logitech G15 Support
-open-source and self hostable musicbots
-no hassle with licences for huge servers

Mumble can be started multiple times with another config, so the only hassle is to edit the cfg thru the wi.
Mumble is totally underestimated imo.

**Comment by ulrichblock** [comment] 2016-02-12 17:13
Duplicate of #66

**Closed by ulrichblock** 2016-02-12 17:13 UTC
